version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tastyigniter-app
    restart: unless-stopped
    environment:
      - APP_NAME=TastyIgniter
      - APP_ENV=production
      - APP_KEY=
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - IGNITER_LOCATION_MODE=multiple
      - IGNITER_CARTE_KEY=

      # Database configuration
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=tastyigniter
      - DB_USERNAME=tastyigniter
      - DB_PASSWORD=secret_password
      - DB_PREFIX=ti_

      # Cache and Session
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120

      # Mail Configuration
      - MAIL_MAILER=log
      - MAIL_FROM_ADDRESS=noreply@tastyigniter.tld
      - MAIL_FROM_NAME=TastyIgniter
    volumes:
      - tastyigniter:/var/www/html
      - tastyigniter-storage:/var/www/html/storage
    depends_on:
      - db
    networks:
      - tastyigniter-network

  nginx:
    image: nginx:alpine
    container_name: tastyigniter-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - tastyigniter:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - tastyigniter-network

  db:
    image: mysql:8
    container_name: tastyigniter-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=tastyigniter
      - MYSQL_USER=tastyigniter
      - MYSQL_PASSWORD=secret_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tastyigniter-network

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tastyigniter-cron
    restart: unless-stopped
    command: bash -c "while true; do php /var/www/html/artisan schedule:run --verbose --no-interaction; sleep 60; done"
    volumes:
      - tastyigniter:/var/www/html
    depends_on:
      - app
    networks:
      - tastyigniter-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tastyigniter-queue
    restart: unless-stopped
    command: php /var/www/html/artisan queue:work
    volumes:
      - tastyigniter:/var/www/html
    depends_on:
      - app
    networks:
      - tastyigniter-network

volumes:
  dbdata:
  tastyigniter:
  tastyigniter-storage:

networks:
  tastyigniter-network:
    driver: bridge
